apiVersion: v1
kind: Service
metadata:
  name: python-api-service
  labels:
    app: python-api
spec:
  selector:
    app: python-api
  ports:
    - protocol: TCP
      port: 80          # Exposed service port
      targetPort: 80    # Container's port
  type: LoadBalancer    # Expose service via AWS ELB (use ClusterIP for internal)
