apiVersion: v1
kind: Service
metadata:
  name: python-api-service
spec:
  type: NodePort
  selector:
    app: python-api
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # Container port
      nodePort: 31981 # Custom NodePort (or omit to get a random one)

