apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
<<<<<<< HEAD
  namespace: default  # Ensure it's deployed in the correct namespace
=======
>>>>>>> f430aea (changes)
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
      - name: python-api
        image: akash8992/python-api-app:latest
        ports:
        - containerPort: 80
      nodeSelector:
<<<<<<< HEAD
        eks.amazonaws.com/compute-type: fargate
=======
        eks.amazonaws.com/compute-type: fargate
>>>>>>> f430aea (changes)
