name: Build

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Install Python dependencies    
      - name: Install dependencies
        run: |
          cd python-api-app  # Move into the correct directory
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      # Trivy file scan
      - name: Trivy file scan
        run: |
          cd python-api-app
          trivy fs . > trivyfd.txt

      # Build the Docker image and push it to Docker Hub  
      - name: Build and push Docker image
        env:
          DOCKER_CLI_ACI: 1
        run: |
          cd python-api-app
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker build -t akash8992/python-api-app:latest .
          docker push akash8992/python-api-app:latest

