name: Build

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Install Python dependencies    
      - name: Debug - Verify Directory
        run: |
          echo "### Checking Current Directory ###"
          pwd
          echo "### Listing Files in Current Directory ###"
          ls -lah
          
          echo "### Checking Home Directory (/home/ubuntu) ###"
          ls -lah /home/ubuntu || echo "Directory not found"

          echo "### Checking Multi-Cloud-Deployment Repository Directory ###"
          ls -lah /home/ubuntu/Multi-Cloud-Deployment || echo "Directory not found"

          echo "### Checking python-api-app Directory ###"
          ls -lah /home/ubuntu/Multi-Cloud-Deployment/python-api-app || echo "Directory not found"


