apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-task-cluster  # Updated cluster name
  region: ap-south-1

fargateProfiles:
  - name: fargate-profile
    selectors:
      - namespace: default
      - namespace: kube-system
    subnets:
      - subnet-0526ffdcfa018ddb9  # Private subnet
      - subnet-04d195f65c4309f27  # Private subnet

managedNodeGroups:
  - name: worker-nodes
    instanceTypes: ["t3.large"]  # Updated instance type
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    privateNetworking: true
    subnets:
      - subnet-01709bf82e8a6b831  # Private subnet
      - subnet-0a5d722b8fa665565  # Private subnet
